### ISSUE TITLE
Clean docker cache periodically

### ISSUE THREAD

**Issue by emranbm** [emranbm/SahaBee#19]
Currently, the pulled images on deployments remain in the production server forever.  
There should be a corn job to clean docker cache (i.e. `docker system prune -a`) periodically.

**Comment by DipayanP007** [comment]
Hey @emranbm I can work on this. Can you assign me this?

**Comment by emranbm** [comment]
Hi @DipayanP007,
Sure, that's my pleasure.
Thanks

**Comment by DipayanP007** [comment]
Hey @emranbm one question. You want a bash script right executing the command?

**Comment by emranbm** [comment]
> Hey @emranbm one question. You want a bash script right executing the command?

Not actually. We need to have it completely working.
**DoD:** A step in [deployment script](https://github.com/emranbm/SahaBee/blob/master/deployment/ansible/deploy.yml) is added so that creates a cron job that periodically (e.g. weekly) runs the command `docker system prune -a`.  
For more details about the _cron_ task in ansible, [this link](https://docs.ansible.com/ansible/2.9/modules/cron_module.html) may help.
